import os
import requests
from crewai import Agent, Task, Crew, Process
from langchain_anthropic import ChatAnthropic

# API Keys from environment variables
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")

os.environ["ANTHROPIC_API_KEY"] = ANTHROPIC_API_KEY

# Language Model
llm = ChatAnthropic(
    model="claude-haiku-4-5-20251001",
    temperature=0.7
)

# Agents
research_agent = Agent(
    role="GRC Research Specialist",
    goal="Research latest GRC and cybersecurity news and summarize key insights",
    backstory="""You are an expert in GRC frameworks and 
    cybersecurity compliance with deep knowledge of CIS, 
    NIST, and ISO 27001. You work for Trinity6, an AI 
    powered cybersecurity company.""",
    llm=llm,
    verbose=True
)

content_agent = Agent(
    role="Content Strategist",
    goal="Draft engaging LinkedIn posts about GRC and cybersecurity for Trinity6",
    backstory="""You are a skilled content writer 
    specializing in cybersecurity and compliance topics 
    for professional audiences. You create content that 
    attracts potential clients for Trinity6.""",
    llm=llm,
    verbose=True
)

# Tasks
research_task = Task(
    description="""Research the latest updates and best 
    practices around CIS benchmarks and GRC compliance 
    for small and medium businesses. Find the top 3 
    most important insights that businesses should know 
    right now.""",
    expected_output="""A concise summary of 3 key GRC 
    insights with practical implications for SMB 
    organizations.""",
    agent=research_agent
)

content_task = Task(
    description="""Using the research provided, draft a 
    professional and engaging LinkedIn post about GRC 
    compliance tips for small businesses. The post should 
    position Trinity6 as an expert in cybersecurity and 
    GRC automation. Keep it under 200 words.""",
    expected_output="""A ready to publish LinkedIn post 
    that is professional, engaging, and positions 
    Trinity6 as a cybersecurity expert.""",
    agent=content_agent
)

# Telegram Function
def send_to_telegram(message):
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message,
        "parse_mode": "HTML"
    }
    response = requests.post(url, json=payload)
    if response.status_code == 200:
        print("Message sent to Telegram successfully!")
    else:
        print("Failed to send message")
        print(response.json())

# Run Crew
crew = Crew(
    agents=[research_agent, content_agent],
    tasks=[research_task, content_task],
    process=Process.sequential,
    verbose=True
)

print("Starting Trinity6 AI Agents...")
result = crew.kickoff()

message = f"""
<b>🛡️ Trinity6 Daily Report</b>

<b>GRC Research & Content Update</b>

{result}

<i>Generated by Trinity6 AI Assistant</i>
"""

send_to_telegram(message)
print("\n=== FINAL OUTPUT ===")
print(result)
